// <auto-generated />
using System;
using CryptoBankBackend.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CryptoBankBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191130143346_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CryptoBankBackend.Core.Models.Entities.OperationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Operation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -466.54000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 957, DateTimeKind.Unspecified).AddTicks(9630), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Argent pour OnePlus 5T",
                            RecipientEmail = "maman@gmail.com",
                            TransactionNumber = "9ca1cfe8-d7ba-4815-b545-78a3938b132d",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = -466.54000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2410), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Remboursement des courses Auchant",
                            RecipientEmail = "copine@gmail.com",
                            TransactionNumber = "2d184aca-2e21-4a58-a9c0-a4b809e7510c",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = -12.01,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2542), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tomate et citronade",
                            RecipientEmail = "mamy@gmail.com",
                            TransactionNumber = "9f11515b-3a83-40a5-ad05-821c3d2fb331",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = -7.29,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2558), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bière entre poto",
                            RecipientEmail = "benjamin@gmail.com",
                            TransactionNumber = "d112014c-994b-4e8b-82ec-b3f46a5e6024",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = -10.5,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2563), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bière entre poto",
                            RecipientEmail = "timothee@gmail.com",
                            TransactionNumber = "bff01f1c-0dda-4329-b27f-9ac2977eb93d",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = -5.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2575), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bière entre poto",
                            RecipientEmail = "jon@gmail.com",
                            TransactionNumber = "1d1a89ef-113d-46d4-9a53-f52d40f48e92",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = -594.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2584), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Voyage Argentine",
                            RecipientEmail = "manon@gmail.com",
                            TransactionNumber = "5ff7f234-2267-4420-af74-1de76f93e0fe",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = -84.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2587), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Nourriture Lecler courses",
                            RecipientEmail = "aurore@gmail.com",
                            TransactionNumber = "00d6e0d2-0a79-4d71-8066-113b109d3d2d",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2632), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Café pause boulot",
                            RecipientEmail = "collegue@gmail.com",
                            TransactionNumber = "2cb51d2c-4b14-4301-8ba5-77b938a5d0b7",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2639), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Encore un autre café pause boulot",
                            RecipientEmail = "collegue_sympa@gmail.com",
                            TransactionNumber = "c36ebd5c-7fa7-421b-911d-b6de183f3399",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2642), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Encore Encore un autre café pause boulot",
                            RecipientEmail = "collegue_sympa_2@gmail.com",
                            TransactionNumber = "28fd96ff-915a-4852-8f27-52355aab915c",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = -8.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2645), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "En route vers la promotion en offrant une biere au patron",
                            RecipientEmail = "patron@gmail.com",
                            TransactionNumber = "4b834e30-515c-4537-a2e0-c63add568cbc",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 20.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2649), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Pour le resto de lundi au boulot ! Merci !",
                            RecipientEmail = "jepaiemesdettes@gmail.com",
                            TransactionNumber = "dd962df0-027f-49e6-82a0-d2328ad014e3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2652), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Café du matin",
                            RecipientEmail = "machineacafe@gmail.com",
                            TransactionNumber = "e311fa1e-c746-4180-9b80-23b8c7c89550",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2658), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Café de l'après midi",
                            RecipientEmail = "machineacafe@gmail.com",
                            TransactionNumber = "d51cff7f-20cb-435c-b065-24983866f392",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2662), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Café du soir",
                            RecipientEmail = "machineacafe@gmail.com",
                            TransactionNumber = "c76a0bb2-0747-475f-9331-a60dc0b229be",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = -2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2665), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Café de la nuit",
                            RecipientEmail = "machineacafe@gmail.com",
                            TransactionNumber = "5059d7c7-0fa1-4e15-a3bc-3a39857c1957",
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            Amount = 2.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2669), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "C'est pour le café de mardi",
                            RecipientEmail = "collegueacafe@gmail.com",
                            TransactionNumber = "e079b106-b15e-458a-b90e-904d7fec9666",
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Amount = 50.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2672), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Repas CE",
                            RecipientEmail = "cedelaboite@gmail.com",
                            TransactionNumber = "2af45dcc-1b0f-495a-9968-047ad7fb89ed",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Amount = 500.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2675), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Noel pour mon cherie !",
                            RecipientEmail = "cedelaboite@gmail.com",
                            TransactionNumber = "29c0dfbd-4d09-4dd2-ac64-43c5138a2165",
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Amount = -1.6200000000000001,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2678), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tranche de pain",
                            RecipientEmail = "jaifaim@gmail.com",
                            TransactionNumber = "a042efbb-2379-49d7-bcaf-0bbedb3e3b56",
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Amount = -1.45,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2682), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Tranche de pain le retour",
                            RecipientEmail = "jaitresfaim@gmail.com",
                            TransactionNumber = "f5fa8253-e8ba-4830-b3c0-cb00dd9799d5",
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            Amount = -4.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2687), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "00e71c15-271c-4446-95b4-8fa65f29d42c",
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Amount = -3.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2691), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "f51b6890-1adc-4fe9-917b-8e7e63f655f6",
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            Amount = -3.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2694), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "9caa93b0-71e6-4f50-a6f2-fe7d6a317aac",
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Amount = -3.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2698), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "12d24383-7e48-4311-a345-f813426fe968",
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            Amount = -3.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2701), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "717a774b-3053-4ac8-b3c7-12334d1672ad",
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Amount = -3.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2704), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "3dd634ed-45be-478c-b789-abcbb4c33404",
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            Amount = -4.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2707), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "de205ca0-cf8b-4f89-ab49-8ffa9ac48e0d",
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            Amount = -7.9900000000000002,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2710), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Location de film",
                            RecipientEmail = "rentdvd@gmail.com",
                            TransactionNumber = "9ec886e4-d400-4f69-ad56-c9c8680351c4",
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            Amount = 24.120000000000001,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2715), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Courses Auchant",
                            RecipientEmail = "encouple@gmail.com",
                            TransactionNumber = "79e70456-56cd-4581-afaf-c4b5987f7dcf",
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            Amount = 24.120000000000001,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2718), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Remboursement resto soirée",
                            RecipientEmail = "encouple@gmail.com",
                            TransactionNumber = "317a1179-f367-4851-9a0e-b82f0cf23b04",
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            Amount = -7.2999999999999998,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2721), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Verre en ville",
                            RecipientEmail = "copain@gmail.com",
                            TransactionNumber = "7d4cbb86-e9eb-4f45-a708-03df0f57a5ad",
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            Amount = -6.5,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2726), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Kebab",
                            RecipientEmail = "copain@gmail.com",
                            TransactionNumber = "50238ff9-0fe1-4aec-98f6-ac14c7204dcc",
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            Amount = 120.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2729), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Cadeau Montre",
                            RecipientEmail = "wow@gmail.com",
                            TransactionNumber = "d51b3e4b-06e9-4797-9442-43620b8f69cf",
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Amount = -28.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2732), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Soirée Kebab",
                            RecipientEmail = "copain@gmail.com",
                            TransactionNumber = "127acefe-7c79-4fa7-9f7c-038c843e1671",
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            Amount = -16.0,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2735), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Salle de sport",
                            RecipientEmail = "workout@gmail.com",
                            TransactionNumber = "8d970e27-e473-46c6-8c8a-f29e61d53b37",
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            Amount = -12.5,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2738), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Soiré ciné",
                            RecipientEmail = "copain@gmail.com",
                            TransactionNumber = "e0715adb-f810-4a46-820d-c79d2b342cff",
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            Amount = -6.5,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2743), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Kebab",
                            RecipientEmail = "copain@gmail.com",
                            TransactionNumber = "f39097b0-41d5-442d-a642-fd3d019e59f5",
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            Amount = 50.5,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 958, DateTimeKind.Unspecified).AddTicks(2746), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Rembousement pro",
                            RecipientEmail = "company@gmail.com",
                            TransactionNumber = "2d5a5a45-6012-4605-a3e4-bb79a19bc6d0",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("CryptoBankBackend.Core.Models.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("Credits")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTimeOffset?>("ModifiedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 953, DateTimeKind.Unspecified).AddTicks(3575), new TimeSpan(0, 0, 0, 0, 0)),
                            Credits = 2265.0,
                            Email = "stephan.arnas@gmail.com",
                            FirstName = "Stephan",
                            LastName = "Arnas",
                            Password = "Aze123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2019, 11, 30, 14, 33, 45, 953, DateTimeKind.Unspecified).AddTicks(4283), new TimeSpan(0, 0, 0, 0, 0)),
                            Credits = 125.0,
                            Email = "remond.dumond@gmail.com",
                            FirstName = "Remond",
                            LastName = "Dumond",
                            Password = "Aze123"
                        });
                });

            modelBuilder.Entity("CryptoBankBackend.Core.Models.Entities.OperationEntity", b =>
                {
                    b.HasOne("CryptoBankBackend.Core.Models.Entities.UserEntity", "User")
                        .WithMany("Operations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
